// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgataizflrtvlpdrsvwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnYXRhaXpmbHJ0dmxwZHJzdndhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDU0NTEsImV4cCI6MjA1ODA4MTQ1MX0.nqwdigzG2o76AYQG6Vn4sXpMkAeYKKV0OhK-G_pnLl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);